Lillian/updating
oslabs-beta/ReacType-55-Team pull request #8
Opened 2023-02-20 19:17 UTC by lillwimberly

2023-02-20 19:30 UTC, brett-webster approved these changes
Thanks Lillian!

2023-02-20 20:12 UTC, brett-webster requested changes
Great news, thanks!  Spelling suggestion line 62 in the dependencies, also pasted below (compontents --> components):

}, [currentComponent, compontents]); // Lillian added another dependency here to utilize useEffect

2023-02-21 01:02 UTC, wang9hu approved these changes

2023-02-21 01:03 UTC, brett-webster approved these changes

2023-02-21 01:03 UTC, wang9hu approved these changes

2023-02-21 01:03 UTC, merged